import type { Title, Genre, Profile, Plan, Notification, LiveChannel, WatchHistoryItem } from './types';

// Curated Pexels imagery (real, stable URLs)
const img = (id: string, w = 600, h = 900) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}&h=${h}&fit=crop`;
const bd = (id: string, w = 1600, h = 900) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}&h=${h}&fit=crop`;

// Royalty-free HLS test streams (Mux/Cloudflare) — public, reliable
const HLS_DEMO = 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8';
const HLS_Tears = 'https://test-streams.mux.dev/test_001/stream.m3u8';
const MP4_BBB = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4';
const MP4_Sintel = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4';
const MP4_Tears = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4';
const MP4_Elephants = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4';
const MP4_ForBigger = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4';

export const TITLES: Title[] = [
  {
    id: 'l_tv9',
    title: 'TV9 Kannada Live',
    type: 'live',
    year: 2026,
    rating: 'U',
    imdb: 9.6,
    match: 99,
    duration: 'Live 24x7',
    genres: ['News', 'Live TV'],
    languages: ['Kannada'],
    description: 'TV9 Kannada Live 24x7 News Channel. Watch live breaking news, Karnataka updates, and prime-time discussions.',
    longDescription: 'TV9 Kannada is Karnataka\'s No.1 Kannada news channel streaming live 24x7. Stay updated with live breaking news, state political updates, sports, entertainment, and top news discussions broadcast directly in HD quality.',
    cast: ['TV9 Kannada News Anchors'],
    director: 'TV9 Network',
    studio: 'TV9 Kannada Live',
    poster: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=1200&auto=format&fit=crop&q=80',
    logo: 'TV9 KANNADA',
    badge: 'LIVE 24x7',
    trending: true,
    isOriginal: false,
    isNew: true,
    isPremium: false,
    tags: ['4K HD', 'Live Broadcast', 'TV9 News'],
    videoUrl: 'https://www.youtube.com/embed/FL1ZcMOhDD8?autoplay=1',
    trailerUrl: 'https://www.youtube.com/embed/FL1ZcMOhDD8?autoplay=1',
  },
  {
    id: 't_custom_rithamaya',
    title: 'Rithamaya: From Soil to Soul',
    type: 'original',
    year: 2026,
    rating: 'U',
    imdb: 9.2,
    match: 99,
    duration: '5m 12s',
    genres: ['Documentary'],
    languages: ['Kannada', 'English', 'Tamil', 'Telugu'],
    description: 'An organic journey of wellness. Discover the ancient secret of 35+ natural ingredients blended to nourish your body, mind, and soul.',
    longDescription: 'Rithamaya: From Soil to Soul takes you on a visually spectacular journey through the organic fields where 6 types of millets, rare grains, rich nuts, and medicinal leaves like Jamun and Guava are harvested. Learn how this 100% natural health mix powder is crafted without preservatives, added colors, or sugar to deliver pure calcium, immunity, and energy to your family.',
    cast: ['Naveen Kumar', 'Dr. Shalini Hegde'],
    director: 'Santhosh Rai',
    studio: 'StreamVerse Health & Wellness',
    poster: '/images/rithamaya_promo.jpg',
    backdrop: '/images/rithamaya_promo.jpg',
    logo: 'RITHAMAYA',
    badge: 'MUST WATCH',
    trending: true,
    isOriginal: true,
    isNew: true,
    isPremium: false,
    tags: ['4K Ultra HD', 'Dolby Atmos', '100% Natural'],
    videoUrl: '/uploads/video_1785327490474_422.mp4',
    trailerUrl: '/uploads/video_1785327490474_422.mp4',
  },
  {
    id: 't_coming_last_shift',
    title: 'Last Shift',
    type: 'original',
    year: 2026,
    rating: 'U/A 16+',
    imdb: 8.8,
    match: 97,
    duration: 'Coming Soon',
    genres: ['Horror', 'Thriller'],
    languages: ['Kannada', 'Tamil', 'Telugu', 'Hindi'],
    description: 'COMING SOON IN CINEMAS. Some shifts end. Others never do. Tonight, you\'re not alone.',
    longDescription: 'A rookie police officer is tasked with taking the last shift at a transitioning police station. Little does she know that the precinct holds a dark, malevolent history connected to a notorious cult leader. As the night deepens, paranormal events escalate into a horrifying fight for her life and sanity.',
    cast: ['Parul Yadav', 'Shraddha Srinath', 'Achyuth Kumar'],
    director: 'Pawan Kumar',
    studio: 'Ka TV Presents',
    poster: '/images/last_shift.jpg',
    backdrop: '/images/last_shift.jpg',
    logo: 'LAST SHIFT',
    badge: 'COMING SOON',
    trending: true,
    isOriginal: true,
    isNew: false,
    isComingSoon: true,
    tags: ['Atmos', 'Cinemas'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-stars-in-space-background-1611-large.mp4',
    trailerUrl: 'https://assets.mixkit.co/videos/preview/mixkit-stars-in-space-background-1611-large.mp4',
  },
  {
    id: 't_coming_addict',
    title: 'Addict',
    type: 'original',
    year: 2026,
    rating: 'U/A 13+',
    imdb: 9.0,
    match: 98,
    duration: 'Streaming Soon',
    genres: ['Drama', 'Thriller'],
    languages: ['Kannada'],
    description: 'STREAMING SOON. Behind every scroll, someone is falling apart. An emotional story of a girl who traded her real life for a virtual world.',
    longDescription: 'Inspired by real-life events. Addict follows the gripping emotional journey of a young girl whose innocent social media habits spiral into a screen addiction, isolating her from family, dreams, and her own identity. Can she break the virtual spell and reclaim her real life?',
    cast: ['Rukmini Vasanth', 'Sanjana Anand'],
    director: 'Hemanth M Rao',
    studio: 'Ka TV Originals',
    poster: '/images/addict.jpg',
    backdrop: '/images/addict.jpg',
    logo: 'ADDICT',
    badge: 'STREAMING SOON',
    trending: true,
    isOriginal: true,
    isNew: false,
    isComingSoon: true,
    tags: ['1080p', 'Ka TV'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-stars-in-space-background-1611-large.mp4',
    trailerUrl: 'https://assets.mixkit.co/videos/preview/mixkit-stars-in-space-background-1611-large.mp4',
  },
  {
    id: 't_katv',
    title: 'Ka TV',
    type: 'original',
    year: 2026,
    rating: 'U/A 13+',
    imdb: 9.5,
    match: 99,
    duration: 'Live Channel',
    genres: ['Drama', 'Action', 'Romance'],
    languages: ['Kannada'],
    description: 'ನಮ್ಮ ಕಥೆಗಳು ನಮ್ಮ ಕನ್ನಡ (Our Stories, Our Kannada). Experience live Kannada entertainment, blockbuster movies, original series, and local sports events in high definition.',
    longDescription: 'Ka TV is the premier destination for Kannada entertainment, bringing together local stories, news, series, movies, and sports. Stay connected with the heart of Karnataka through our curated collection of cultural, general entertainment, and blockbuster films.',
    cast: ['Puneeth Rajkumar', 'Kichcha Sudeep', 'Darshan', 'Yash'],
    director: 'StreamVerse Channels',
    studio: 'Ka TV Network',
    poster: '/uploads/hero_banner.png',
    backdrop: '/uploads/hero_banner.png',
    logo: 'ಕ TV',
    badge: 'LIVE NOW',
    trending: true,
    isOriginal: true,
    isFeatured: true,
    isNew: true,
    tags: ['1080p', 'Live', 'Atmos'],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-stars-in-space-background-1611-large.mp4',
    trailerUrl: 'https://assets.mixkit.co/videos/preview/mixkit-stars-in-space-background-1611-large.mp4',
  },
  {
    id: 't1',
    title: 'Crimson Horizon',
    type: 'original',
    year: 2024,
    rating: 'U/A 16+',
    imdb: 8.7,
    match: 98,
    duration: '2h 18m',
    genres: ['Sci-Fi', 'Thriller', 'Drama'],
    languages: ['English', 'Spanish', 'Hindi', 'Japanese'],
    description: 'When Earth\'s last colony loses contact, a lone pilot crosses the crimson horizon to uncover a truth that rewrites humanity.',
    longDescription: 'Set against the dying light of a colonized Mars, Commander Ava Reyes embarks on a perilous solo mission to restore communications with Outpost Crimson. What she discovers beyond the horizon threatens not just the colony, but the very fabric of human survival. A sweeping sci-fi epic about isolation, sacrifice, and the thin line between hope and despair.',
    cast: ['Zoe Saldana', 'Oscar Isaac', 'Daniel Kaluuya', 'Florence Pugh'],
    director: 'Denis Villeneuve',
    studio: 'StreamVerse Originals',
    poster: img('2899724'),
    backdrop: bd('110854'),
    logo: 'CRIMSON HORIZON',
    badge: '#1 in Movies Today',
    trending: true,
    isOriginal: true,
    isNew: true,
    isPremium: true,
    tags: ['4K Ultra HD', 'HDR', 'Atmos'],
    videoUrl: HLS_DEMO,
    trailerUrl: MP4_Tears,
  },
  {
    id: 't2',
    title: 'The Last Cartographer',
    type: 'movie',
    year: 2023,
    rating: 'U/A 13+',
    imdb: 8.2,
    match: 95,
    duration: '2h 04m',
    genres: ['Adventure', 'Drama'],
    languages: ['English', 'French', 'German'],
    description: 'An aging mapmaker charts one final unknown territory — a forest that redraws itself overnight.',
    longDescription: 'In the remote highlands, reclusive cartographer August Bell takes on his final apprentice. Together they map a forest that shifts its rivers and hills with each dawn, hiding a secret older than memory.',
    cast: ['Anthony Hopkins', 'Timothée Chalamet', 'Saoirse Ronan'],
    director: 'Wes Anderson',
    studio: 'Atlas Films',
    poster: img('1671325'),
    backdrop: bd('268415'),
    badge: 'NEW',
    trending: true,
    isNew: true,
    isPremium: true,
    tags: ['4K Ultra HD', 'HDR'],
    videoUrl: MP4_BBB,
    trailerUrl: MP4_Sintel,
  },
  {
    id: 't3',
    title: 'Neon Requiem',
    type: 'movie',
    year: 2024,
    rating: 'A',
    imdb: 8.9,
    match: 99,
    duration: '2h 31m',
    genres: ['Action', 'Crime', 'Neo-Noir'],
    languages: ['English', 'Korean', 'Japanese'],
    description: 'In a rain-soaked megacity, a retired assassin is pulled back for one contract that breaks every rule she swore to keep.',
    longDescription: 'Neo-Kyoto, 2089. Miko Arashi left the underworld behind. But when a synthetic soul trafficker targets her sister, Miko walks back into the neon rain for one last, impossible contract.',
    cast: ['Park So-dam', 'Masaki Suda', 'Ana de Armas'],
    director: 'Chad Stahelski',
    studio: 'Nightfall Productions',
    poster: img('1615816'),
    backdrop: bd('1615816'),
    logo: 'NEON REQUIEM',
    badge: 'TOP 10',
    trending: true,
    isOriginal: true,
    isPremium: true,
    tags: ['4K Ultra HD', 'HDR', 'Atmos'],
    videoUrl: HLS_Tears,
    trailerUrl: MP4_Tears,
  },
  {
    id: 't4',
    title: 'Wolves of Wintervale',
    type: 'series',
    year: 2024,
    rating: 'U/A 16+',
    imdb: 9.1,
    match: 97,
    duration: '3 Seasons',
    genres: ['Fantasy', 'Drama', 'Political'],
    languages: ['English', 'Hindi', 'Tamil', 'Telugu'],
    description: 'Three noble houses. One frozen throne. The wolves of Wintervale have waited a generation for blood.',
    longDescription: 'In the frozen kingdom of Wintervale, the death of the High King ignites a war between the houses of Ash, Thorne, and Vael. Alliances rot, secrets surface, and the wolves circling the throne are not all human.',
    cast: ['Cillian Murphy', 'Anya Taylor-Joy', 'Idris Elba', 'Lashana Lynch'],
    director: 'Michele Applewood',
    studio: 'StreamVerse Originals',
    poster: img('2422497'),
    backdrop: bd('2422497'),
    logo: 'WOLVES OF WINTERVALE',
    badge: '#1 in Series Today',
    trending: true,
    isOriginal: true,
    isPremium: true,
    seasons: 3,
    tags: ['4K Ultra HD', 'HDR', 'Atmos'],
    videoUrl: HLS_DEMO,
    trailerUrl: MP4_Sintel,
    episodes: [
      { id: 's1e1', season: 1, episode: 1, title: 'The Long Night', duration: '58m', description: 'King Aldric dies. The wolves gather.', thumbnail: bd('2422497'), videoUrl: HLS_DEMO },
      { id: 's1e2', season: 1, episode: 2, title: 'Blood on Snow', duration: '52m', description: 'House Thorne makes its first move.', thumbnail: bd('2422497'), videoUrl: MP4_BBB },
      { id: 's1e3', season: 1, episode: 3, title: 'The Vael Bride', duration: '49m', description: 'A marriage offer hides a blade.', thumbnail: bd('2422497'), videoUrl: MP4_Sintel },
      { id: 's1e4', season: 1, episode: 4, title: 'Oathbreaker', duration: '55m', description: 'An old vow is tested.', thumbnail: bd('2422497'), videoUrl: MP4_Tears },
    ],
  },
  {
    id: 't5',
    title: 'Paper Lanterns',
    type: 'movie',
    year: 2023,
    rating: 'U',
    imdb: 8.0,
    match: 92,
    duration: '1h 48m',
    genres: ['Romance', 'Drama'],
    languages: ['Japanese', 'English'],
    description: 'Two strangers meet each November at the same lantern festival — and never exchange names.',
    longDescription: 'A quiet, decade-spanning romance told across twelve lantern festivals. Kenji and Mei share one night each year, until the year one of them doesn\'t come.',
    cast: ['Masaki Suda', 'Hana Sugisaki'],
    director: 'Hirokazu Kore-eda',
    studio: 'Lantern House',
    poster: img('110854'),
    backdrop: bd('110854'),
    badge: 'NEW',
    isNew: true,
    tags: ['1080p'],
    videoUrl: MP4_Sintel,
  },
  {
    id: 't6',
    title: 'Iron Verdict',
    type: 'series',
    year: 2024,
    rating: 'U/A 16+',
    imdb: 8.5,
    match: 94,
    duration: '2 Seasons',
    genres: ['Legal', 'Crime', 'Drama'],
    languages: ['English', 'Hindi'],
    description: 'A disgraced judge runs a courtroom from a converted bar — dispensing a verdict the law won\'t.',
    longDescription: 'Judge Mara Vance lost her robe and her family to a corruption scandal. Now she runs an underground tribunal for those the system failed, with a jury of strangers and a verdict made of iron.',
    cast: ['Viola Davis', 'Sterling K. Brown', 'Riz Ahmed'],
    director: 'Michele Applewood',
    studio: 'Gavel Pictures',
    poster: img('566885'),
    backdrop: bd('566885'),
    trending: true,
    seasons: 2,
    tags: ['4K Ultra HD'],
    videoUrl: HLS_Tears,
    trailerUrl: MP4_Tears,
    episodes: [
      { id: 'iv1', season: 1, episode: 1, title: 'Opening Statement', duration: '47m', description: 'Mara takes her first off-the-books case.', thumbnail: bd('566885'), videoUrl: HLS_Tears },
      { id: 'iv2', season: 1, episode: 2, title: 'Reasonable Doubt', duration: '44m', description: 'The jury isn\'t who they seem.', thumbnail: bd('566885'), videoUrl: MP4_Tears },
    ],
  },
  {
    id: 't7',
    title: 'Saltwater Saints',
    type: 'movie',
    year: 2022,
    rating: 'U/A 13+',
    imdb: 7.8,
    match: 88,
    duration: '2h 09m',
    genres: ['Drama', 'Sport'],
    languages: ['English', 'Portuguese'],
    description: 'A broken surfer returns to the village that exiled her to train its first women\'s team.',
    longDescription: 'After a career-ending wipeout, big-wave surfer Lani returns to her Hawaiian village to coach a ragtag girls\' team toward the national championship — and face the community she left behind.',
    cast: ['Auli\'i Cravalho', 'Jason Momoa'],
    director: 'Chloé Zhao',
    studio: 'Tidewater Films',
    poster: img('572897'),
    backdrop: bd('572897'),
    tags: ['4K Ultra HD', 'HDR'],
    videoUrl: MP4_BBB,
  },
  {
    id: 't8',
    title: 'The Glasshouse Protocol',
    type: 'series',
    year: 2024,
    rating: 'U/A 16+',
    imdb: 8.8,
    match: 96,
    duration: '1 Season',
    genres: ['Sci-Fi', 'Mystery'],
    languages: ['English', 'German', 'Korean'],
    description: 'Six scientists wake in a sealed greenhouse with no memory — and one of them is the architect.',
    longDescription: 'A locked-room sci-fi mystery. Six strangers wake in a vast glass biome with no memory of how they arrived. As food runs low and the climate inside turns hostile, they must deduce which of them built the trap — and why.',
    cast: ['Bae Doona', 'Daniel Brühl', 'Lupita Nyong\'o'],
    director: 'Bong Joon-ho',
    studio: 'StreamVerse Originals',
    poster: img('3750155'),
    backdrop: bd('3750155'),
    logo: 'THE GLASSHOUSE PROTOCOL',
    badge: 'NEW',
    isOriginal: true,
    isNew: true,
    seasons: 1,
    tags: ['4K Ultra HD', 'HDR', 'Atmos'],
    videoUrl: HLS_DEMO,
    trailerUrl: MP4_Sintel,
    episodes: [
      { id: 'gp1', season: 1, episode: 1, title: 'Germination', duration: '51m', description: 'Six wake. One door. No memory.', thumbnail: bd('3750155'), videoUrl: HLS_DEMO },
      { id: 'gp2', season: 1, episode: 2, title: 'Photosynthesis', duration: '48m', description: 'The lights go off for 12 hours.', thumbnail: bd('3750155'), videoUrl: MP4_Sintel },
    ],
  },
  {
    id: 't9',
    title: 'Midnight Bazaar',
    type: 'movie',
    year: 2023,
    rating: 'U/A 13+',
    imdb: 7.9,
    match: 90,
    duration: '2h 02m',
    genres: ['Romance', 'Comedy', 'Drama'],
    languages: ['Hindi', 'English', 'Tamil'],
    description: 'A street-food vendor and a food critic fall in love over one chaotic night market.',
    longDescription: 'In the neon heart of Mumbai\'s midnight bazaar, a chaat vendor and a jaded food critic have twelve hours, one missing recipe, and a city that never sleeps.',
    cast: ['Vijay Deverakonda', 'Sara Ali Khan'],
    director: 'Zoya Akhtar',
    studio: 'Bazaar Films',
    poster: img('3750155'),
    backdrop: bd('3750155'),
    tags: ['1080p'],
    videoUrl: MP4_ForBigger,
  },
  {
    id: 't10',
    title: 'Apex: The Climb',
    type: 'sport',
    year: 2024,
    rating: 'U',
    imdb: 8.3,
    match: 93,
    duration: '1h 36m',
    genres: ['Documentary', 'Sport'],
    languages: ['English', 'Spanish'],
    description: 'Four climbers. One unclimbed Himalayan face. Forty days above 7,000m.',
    longDescription: 'A breathtaking documentary following four elite alpinists attempting the first ascent of the unclimbed east face of Annapurna IV — a 40-day siege at the edge of human endurance.',
    cast: ['Nirmal Purja', 'Conrad Anker'],
    director: 'Jimmy Chin',
    studio: 'Vertical Pictures',
    poster: img('572897'),
    backdrop: bd('572897'),
    badge: 'NEW',
    isNew: true,
    tags: ['4K Ultra HD', 'HDR'],
    videoUrl: MP4_Elephants,
  },
  {
    id: 't11',
    title: 'Tiny Titans',
    type: 'kids',
    year: 2024,
    rating: 'U',
    imdb: 7.6,
    match: 91,
    duration: '4 Seasons',
    genres: ['Animation', 'Kids', 'Comedy'],
    languages: ['English', 'Hindi', 'Spanish', 'French'],
    description: 'A classroom of super-powered kindergartners save the playground before naptime.',
    longDescription: 'Ms. Quill\'s class of super-powered five-year-olds must defend their playground from the villainous Dr. Naptime — all before the bell rings.',
    cast: ['Voice cast: Tom Kenny', 'Tara Strong'],
    director: 'Pete Browngardt',
    studio: 'StreamVerse Kids',
    poster: img('1005012'),
    backdrop: bd('1005012'),
    isOriginal: true,
    seasons: 4,
    tags: ['1080p'],
    videoUrl: MP4_BBB,
    episodes: [
      { id: 'tt1', season: 1, episode: 1, title: 'First Day of Flight', duration: '22m', description: 'The Titans learn to fly... sort of.', thumbnail: bd('1005012'), videoUrl: MP4_BBB },
    ],
  },
  {
    id: 't12',
    title: 'Static Bloom',
    type: 'movie',
    year: 2024,
    rating: 'A',
    imdb: 8.4,
    match: 95,
    duration: '1h 54m',
    genres: ['Horror', 'Mystery'],
    languages: ['English', 'Korean'],
    description: 'A radio host starts receiving broadcasts from a station that went dark forty years ago.',
    longDescription: 'Late-night DJ Ruby Han receives a transmission from WVL-9, a station that burned down in 1984. The host on the other end is still on air — and he wants a call-in guest.',
    cast: ['Florence Pugh', 'Steven Yeun'],
    director: 'Ari Aster',
    studio: 'Nightfall Productions',
    poster: img('2899724'),
    backdrop: bd('2899724'),
    badge: 'TOP 10',
    trending: true,
    isNew: true,
    tags: ['4K Ultra HD', 'HDR', 'Atmos'],
    videoUrl: MP4_Tears,
    trailerUrl: MP4_Tears,
  },
];

export const GENRES: Genre[] = [
  { id: 'g1', name: 'Action', image: bd('1615816') },
  { id: 'g2', name: 'Drama', image: bd('110854') },
  { id: 'g3', name: 'Sci-Fi', image: bd('3750155') },
  { id: 'g4', name: 'Romance', image: bd('2422497') },
  { id: 'g5', name: 'Horror', image: bd('2899724') },
  { id: 'g6', name: 'Comedy', image: bd('110854') },
  { id: 'g7', name: 'Documentary', image: bd('572897') },
  { id: 'g8', name: 'Animation', image: bd('1005012') },
];

export const PROFILES: Profile[] = [
  { id: 'p1', name: 'Alex', avatar: '🦊', isKids: false, color: '#E50914' },
];

export const PLANS: Plan[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    period: 'forever',
    quality: 'Good',
    resolution: '480p',
    devices: 1,
    features: ['Ad-supported', 'Mobile only', 'Limited library', 'No downloads'],
    color: '#6b7280',
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 699,
    period: 'month',
    quality: 'Best',
    resolution: '4K Ultra HD + HDR',
    devices: 4,
    features: ['No ads', '4K Ultra HD', 'HDR + Dolby Atmos', 'Download on 6 devices', 'All devices', 'StreamVerse Originals'],
    highlight: true,
    badge: 'Most Popular',
    color: '#E50914',
  },
  {
    id: 'vip',
    name: 'VIP',
    price: 1299,
    period: 'month',
    quality: 'Best',
    resolution: '4K Ultra HD + HDR',
    devices: 6,
    features: ['Everything in Premium', 'Early access to Originals', 'Priority live sports', 'Family sharing', 'Concurrent 4K streams', 'Premium support'],
    badge: 'All Access',
    color: '#f59e0b',
  },
];

export const NOTIFICATIONS: Notification[] = [
  { id: 'n1', title: 'New episode available', body: 'Wolves of Wintervale S3 E5 is now streaming.', time: '2m ago', icon: 'play', read: false },
  { id: 'n2', title: 'Crimson Horizon is here', body: 'The StreamVerse Original movie you waited for.', time: '1h ago', icon: 'star', read: false },
  { id: 'n3', title: 'Payment successful', body: 'Your Premium plan renews on Aug 20, 2026.', time: '5h ago', icon: 'card', read: true },
  { id: 'n4', title: 'Live now: Apex Climb', body: 'The summit push is happening right now.', time: '8h ago', icon: 'live', read: true },
];

export const WATCH_HISTORY: WatchHistoryItem[] = [
  { titleId: 't3', progress: 67, watchedAt: 'Yesterday', remainingMin: 42 },
  { titleId: 't4', progress: 23, watchedAt: '2 days ago', remainingMin: 51 },
  { titleId: 't1', progress: 88, watchedAt: '3 days ago', remainingMin: 14 },
  { titleId: 't6', progress: 12, watchedAt: '5 days ago', remainingMin: 41 },
];

export const LIVE_CHANNELS: LiveChannel[] = [
  { id: 'l_7s_music_kn', name: '7S Music Live (7S ಮ್ಯೂಸಿಕ್ 24x7)', category: 'Kannada Music Live', logo: 'https://i.imgur.com/zDiIhdN.png', nowPlaying: '7S Music Non-Stop Sandalwood Hits & Melodies (ಕನ್ನಡ ಸೂಪರ್ ಹಿಟ್ ಹಾಡುಗಳು)', nextUp: '7S Top 10 Countdown', viewers: '4.9M', isLive: true, backdrop: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80', videoUrl: 'https://mumt03.tangotv.in/Dsly5z3H7SMUSIC/index.m3u8' },
  { id: 'l_aaryaa_tv_kn', name: 'Aaryaa TV Live (ಆರ್ಯಾ ಟಿವಿ 24x7)', category: 'Kannada Music Live', logo: 'https://stream.ottlive.co.in/aryatvtamil/logo.png', nowPlaying: 'Aaryaa TV Live Kannada Music & Entertainment (ಆರ್ಯಾ ಟಿವಿ)', nextUp: 'Aaryaa Prime Blockbuster Express', viewers: '3.6M', isLive: true, backdrop: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80', videoUrl: 'https://stream.ottlive.co.in/aryatvtamil/index.m3u8' },
  { id: 'l_tv9_kn', name: 'TV9 Kannada Live (ಟಿವಿ9 ಕನ್ನಡ)', category: 'Kannada News', logo: '📺', nowPlaying: 'TV9 Kannada Live News Bulletin (ಟಿವಿ9 ಕನ್ನಡ ಶೀಘ್ರ ಸುದ್ದಿ)', nextUp: 'TV9 Special Prime Time Report', viewers: '5.4M', isLive: true, backdrop: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=1200&auto=format&fit=crop&q=80', videoUrl: 'https://www.youtube.com/embed/FL1ZcMOhDD8?autoplay=1' },
  { id: 'l_dd_chandana_kn', name: 'DD Chandana (ಡಿಡಿ ಚಂದನ)', category: 'Kannada News', logo: '📺', nowPlaying: 'DD Chandana Live Doordarshan Broadcast', nextUp: 'Kannada Cultural Program', viewers: '1.8M', isLive: true, backdrop: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=1200&auto=format&fit=crop&q=80', videoUrl: 'https://www.youtube.com/embed/FL1ZcMOhDD8?autoplay=1' },
  { id: 't_katv_kn', name: 'Ka TV Live (ಕ TV HD)', category: 'Kannada Live', logo: '📺', nowPlaying: 'ನಮ್ಮ ಕಥೆಗಳು ನಮ್ಮ ಕನ್ನಡ (Live Blockbuster HD)', nextUp: 'Ka TV Prime Cinema', viewers: '4.8M', isLive: true, backdrop: '/uploads/hero_banner.png', videoUrl: '/uploads/video_1785327490474_422.mp4' },
  { id: 'l_dw_english', name: 'DW News English 24x7', category: 'English Live', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Deutsche_Welle_symbol_2012.svg/512px-Deutsche_Welle_symbol_2012.svg.png', nowPlaying: 'DW News Live World Report & Global Documentaries', nextUp: 'DW Conflict Zone', viewers: '5.2M', isLive: true, backdrop: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=1200&auto=format&fit=crop&q=80', videoUrl: 'https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8' },
  { id: 'l_france24_english', name: 'France 24 English 24x7', category: 'English Live', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/France_24_logo.svg/512px-France_24_logo.svg.png', nowPlaying: 'France 24 Live International News & Analysis', nextUp: 'France 24 Culture & The Debate', viewers: '4.8M', isLive: true, backdrop: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=1200&auto=format&fit=crop&q=80', videoUrl: 'https://static.france24.com/live/F24_EN_LO_HLS/live_tv.m3u8' },
  { id: 'l_redbull', name: 'Red Bull TV English', category: 'Sports', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Red_Bull_TV_logo.svg/512px-Red_Bull_TV_logo.svg.png', nowPlaying: 'Red Bull Extreme Sports Live', nextUp: 'Formula 1 & Action Live', viewers: '4.2M', isLive: true, backdrop: bd('572897'), videoUrl: 'https://rbmn-live.akamaized.net/hls/live/591070/GEO_IN/index.m3u8' },
  { id: 'l_nasa_tv', name: 'NASA TV Space Live', category: 'English Live', logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg', nowPlaying: 'NASA Live ISS Earth View & Space Exploration', nextUp: 'Artemis Moon Mission Special', viewers: '3.9M', isLive: true, backdrop: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80', videoUrl: 'https://ntv1.akamaized.net/hls/live/2014075/NASA-TV-Media/master.m3u8' },
  { id: 'l_bloomberg_tv', name: 'Bloomberg TV Finance 24x7', category: 'English Live', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Bloomberg_L.P._logo.svg/512px-Bloomberg_L.P._logo.svg.png', nowPlaying: 'Bloomberg Global Markets & Financial News Live', nextUp: 'Bloomberg Technology & Markets Hour', viewers: '3.1M', isLive: true, backdrop: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&auto=format&fit=crop&q=80', videoUrl: 'https://live-bloomberg-us.amagi.tv/playlist.m3u8' },
  { id: 'l_9xm', name: '9XM Music (IPTV-org)', category: 'Music', logo: 'https://xstreamcp-assets-msp.streamready.in/assets/LIVETV/LIVECHANNEL/LIVETV_LIVETVCHANNEL_9XM/images/LOGO_HD/image.png', nowPlaying: '9XM Non-Stop Bollywood Hits', nextUp: 'Smash Hits Hour', viewers: '3.6M', isLive: true, backdrop: bd('110854'), videoUrl: 'https://9xjio.wiseplayout.com/9XM/master.m3u8' },
  { id: 'l_9x_jalwa', name: '9X Jalwa Classic Songs', category: 'Music', logo: 'https://xstreamcp-assets-msp.streamready.in/assets/LIVETV/LIVECHANNEL/LIVETV_LIVETVCHANNEL_9X_JALWA/images/LOGO_HD/image.png', nowPlaying: 'Evergreen 90s & 2000s Hits Non-Stop', nextUp: 'Jalwa Golden Era Melodies', viewers: '2.8M', isLive: true, backdrop: bd('110854'), videoUrl: 'https://b.jsrdn.com/strm/channels/9xjalwa/master.m3u8' },
  { id: 'l_9x_tashan', name: '9X Tashan Punjabi Hits', category: 'Music', logo: 'https://xstreamcp-assets-msp.streamready.in/assets/LIVETV/LIVECHANNEL/LIVETV_LIVETVCHANNEL_9X_TASHAN/images/LOGO_HD/image.png', nowPlaying: '9X Tashan Punjabi Party Beats', nextUp: 'Bhangra Special Hour', viewers: '2.2M', isLive: true, backdrop: bd('110854'), videoUrl: 'https://amg01281-9xmediapvtltd-9xtashan-samsungin-xz1sd.amagi.tv/playlist/amg01281-9xmediapvtltd-9xtashan-samsungin/playlist.m3u8' },
  { id: 'l_b4u_music', name: 'B4U Music Hits 24x7', category: 'Music', logo: 'https://dtil.tmsimg.com/assets/s90012_ld_h15_aa.png?lock=720x540', nowPlaying: 'B4U Aawaz De Kahan Hai Non-stop', nextUp: 'B4U First Look & Hits', viewers: '1.9M', isLive: true, backdrop: bd('110854'), videoUrl: 'https://amg00778-b4unetworksltd-b4umusic-samsungin-cl2cs.amagi.tv/playlist/amg00778-b4unetworksltd-b4umusic-samsungin/playlist.m3u8' },
  { id: 'l_aajtak', name: 'Aaj Tak HD (IPTV-org)', category: 'News', logo: 'https://xstreamcp-assets-msp.streamready.in/assets/LIVETV/LIVECHANNEL/LIVETV_LIVETVCHANNEL_AAJ_TAK/images/LOGO_HD/image.png', nowPlaying: 'Aaj Tak Live HD Prime News', nextUp: 'Super 100 Bulletin', viewers: '3.4M', isLive: true, backdrop: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=1200&auto=format&fit=crop&q=80', videoUrl: 'https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8' },
];

export const TRENDING_SEARCHES = ['Crimson Horizon', 'Wolves of Wintervale', 'Neon Requiem', 'Live Cricket', 'Tiny Titans', 'Glasshouse Protocol'];

// Helpers
export const getTitle = (id: string) => TITLES.find((t) => t.id === id);
export const byType = (type: string) => TITLES.filter((t) => t.type === type);
export const trending = () => TITLES.filter((t) => t.trending);
export const latest = () => TITLES.filter((t) => t.isNew);
export const topRated = () => [...TITLES].sort((a, b) => b.imdb - a.imdb).slice(0, 10);
export const originals = () => TITLES.filter((t) => t.isOriginal);
export const byGenre = (g: string) => TITLES.filter((t) => t.genres.includes(g));
